version: "3"

services:
  postgres:
    image: "postgres:latest"
    container_name: "caravelas-postgres"
    volumes:
      - './volumes/postgres:/var/lib/postgresql/data'
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${DB_NAME:-caravelas}
      POSTGRES_USER: ${DB_USERNAME:-caravelas}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-secret}

  caravelas-api:
    image: "node:16-alpine"
    env_file: '.env.docker'
    container_name: "caravelas-api"
    volumes:
      - "./:/source"
    working_dir: /source
    depends_on:
      - postgres
    ports:
      - "8000:8000"
    command: sh -c "yarn && yarn start"